### PR TITLE
Fix course code lookup

### PR DESCRIPTION
**Pull request by djungyvr**

### CODE REVIEW

**Comment by djungyvr** [comment]
Fixes #1

**Comment by edmundseow** [comment]
Preliminary testing shows that it is working. I'm running a few more tests to confirm.

**Comment by justin0022** [comment]
That's good to hear!

**Comment by edmundseow** [comment]
Spoke too soon. Once the 2017 syllabi are in the output directory, only the 2017 syllabi are displayed.

**Pull request merged**
